### PR TITLE
show bug fix.

### LINKED ISSUE #39: paper-typeahead results should not be shown unless the input has focus.

### PR DESCRIPTION
**Pull request by samccone**
This is to fix a bug that was introduced in the last release where, if
the typed value or backing data changed, the results would be opened
even if the user did not have focus.

Fixes #39

### CODE REVIEW

File: paper-typeahead.js [hunk 1]
```diff
@@ -249,10 +255,19 @@
...
       });
     },
 
+    /**
+     * @private
+     * @param {!Array<?>} results
+     * @return {boolean}
+     */
+    _canShowResults: function(results) {
+      return document.activeElement === this.$.input && results && results.length > 0;
```
Comment (hungyao) [inline paper-typeahead.js]: To work on shadow dom, this needs something like `document.activeElement === this.$.input || this.root.activeElement === this.$.input` unfortunately :-(

Comment (samccone) [reply paper-typeahead.js]: +1 done
